// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Incentive$Type } from "./Incentive";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Incentive"]: Incentive$Type;
    ["contracts/incentives/Incentive.sol:Incentive"]: Incentive$Type;
  }
}
