// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { SlotDerivation$Type } from "./SlotDerivation";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SlotDerivation"]: SlotDerivation$Type;
    ["@openzeppelin/contracts/utils/SlotDerivation.sol:SlotDerivation"]: SlotDerivation$Type;
  }
}
