// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SlotDerivation$Type } from "./SlotDerivation";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SlotDerivation"]: SlotDerivation$Type;
    ["@openzeppelin/contracts/utils/SlotDerivation.sol:SlotDerivation"]: SlotDerivation$Type;
  }

  interface ContractTypesMap {
    ["SlotDerivation"]: GetContractReturnType<SlotDerivation$Type["abi"]>;
    ["@openzeppelin/contracts/utils/SlotDerivation.sol:SlotDerivation"]: GetContractReturnType<SlotDerivation$Type["abi"]>;
  }
}
