// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SlotDerivation$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SlotDerivation",
  "sourceName": "@openzeppelin/contracts/utils/SlotDerivation.sol",
  "abi": [],
  "bytecode": "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212207b531b13e273352fbefc419f7da37380dbcd01f5d099c8d775d98f7cbec61d8e64736f6c634300081a0033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212207b531b13e273352fbefc419f7da37380dbcd01f5d099c8d775d98f7cbec61d8e64736f6c634300081a0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SlotDerivation",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SlotDerivation$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/SlotDerivation.sol:SlotDerivation",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SlotDerivation$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SlotDerivation",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SlotDerivation$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/SlotDerivation.sol:SlotDerivation",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SlotDerivation$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SlotDerivation",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SlotDerivation$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/SlotDerivation.sol:SlotDerivation",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SlotDerivation$Type["abi"]>>;
}
