// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC721MintAction$Type } from "./ERC721MintAction";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC721MintAction"]: ERC721MintAction$Type;
    ["contracts/actions/ERC721MintAction.sol:ERC721MintAction"]: ERC721MintAction$Type;
  }

  interface ContractTypesMap {
    ["ERC721MintAction"]: GetContractReturnType<ERC721MintAction$Type["abi"]>;
    ["contracts/actions/ERC721MintAction.sol:ERC721MintAction"]: GetContractReturnType<ERC721MintAction$Type["abi"]>;
  }
}
