// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC721MintAction$Type } from "./ERC721MintAction";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC721MintAction"]: ERC721MintAction$Type;
    ["contracts/actions/ERC721MintAction.sol:ERC721MintAction"]: ERC721MintAction$Type;
  }
}
