[profile.default]
optimizer = true
optimizer_runs = 10_000
build_info = true
src = "src"
out = "out"
libs = ["lib"]

[doc]
title = "Boost Protocol Docs"
repository = "https://github.com/rabbitholegg/boost-protocol"
