[profile.default]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
optimizer = true
optimizer_runs = 10_000
out = 'out'
src = 'contracts'
test = 'test'
script = 'script/solidity'
cache_path  = 'cache_forge'
libs = ['node_modules', 'lib']
solc_version = '0.8.26'
evm_version = 'cancun'
fs_permissions = [{access = "read-write", path = "./deploys"}]
remappings=[
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  '@openzeppelin-upgrades/contracts/=lib/openzeppelin-contracts-upgradeable/contracts/',
  'forge-std/=lib/forge-std/src/',
  '@solady/=lib/solady/src/',
  '@boost/contracts/=contracts/'
]

[doc]
title = "Boost Protocol Docs"
repository = "https://github.com/boostxyz/boost-protocol"

[etherscan]
sepolia = { key = "${MAIN_ETHERSCAN_API_KEY}", chain = "sepolia" }
base-sepolia = { key = "${BASE_ETHERSCAN_API_KEY}", chain = "base-sepolia" }
