[profile.default]
build_info = true
optimizer = true
optimizer_runs = 10_000
out = 'out'
src = 'contracts'
test = 'test'
cache_path  = 'cache_forge'
libs = ['node_modules', 'lib']
solc_version = '0.8.26'
evm_version = 'cancun'

remappings=[
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  '@openzeppelin-upgrades/contracts/=lib/openzeppelin-contracts-upgradeable/contracts/',
  'ds-test/=lib/forge-std/lib/ds-test/src/',
  'forge-std/=lib/forge-std/src/',
  '@solady/=lib/solady/src/',
  '@eigenlayer/contracts/=lib/eigenlayer-contracts/src/contracts/',
  '@eigenlayer-middleware/=lib/eigenlayer-middleware/src/',
  'eigenlayer-contracts/=lib/eigenlayer-middleware/lib/eigenlayer-contracts/',
  '@eth-infinitism/account-abstraction/=lib/account-abstraction/contracts/',
  '@boost/contracts/=contracts/'
]

[doc]
title = "Boost Protocol Docs"
repository = "https://github.com/rabbitholegg/boost-protocol"
