[profile.default]
build_info = true
optimizer = true
optimizer_runs = 10_000

out = 'out'
src = 'contracts'
test = 'test'
cache_path  = 'cache_forge'
libs = ['node_modules', 'lib']

[doc]
title = "Boost Protocol Docs"
repository = "https://github.com/rabbitholegg/boost-protocol"
