// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BoostLib$Type } from "./BoostLib";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BoostLib"]: BoostLib$Type;
    ["contracts/shared/BoostLib.sol:BoostLib"]: BoostLib$Type;
  }

  interface ContractTypesMap {
    ["BoostLib"]: GetContractReturnType<BoostLib$Type["abi"]>;
    ["contracts/shared/BoostLib.sol:BoostLib"]: GetContractReturnType<BoostLib$Type["abi"]>;
  }
}
