// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { BoostLib$Type } from "./BoostLib";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BoostLib"]: BoostLib$Type;
    ["contracts/shared/BoostLib.sol:BoostLib"]: BoostLib$Type;
  }
}
