// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface BoostLib$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "BoostLib",
  "sourceName": "contracts/shared/BoostLib.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220c69b9077723cacbb5645b0dfe38a14dda9c9c2e1238d53afc4f1f0a3d4d1bebf64736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220c69b9077723cacbb5645b0dfe38a14dda9c9c2e1238d53afc4f1f0a3d4d1bebf64736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "BoostLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<BoostLib$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/shared/BoostLib.sol:BoostLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<BoostLib$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "BoostLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<BoostLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/shared/BoostLib.sol:BoostLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<BoostLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "BoostLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<BoostLib$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/shared/BoostLib.sol:BoostLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<BoostLib$Type["abi"]>>;
}
