// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { BasePaymaster$Type } from "./BasePaymaster";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BasePaymaster"]: BasePaymaster$Type;
    ["@eth-infinitism/account-abstraction/core/BasePaymaster.sol:BasePaymaster"]: BasePaymaster$Type;
  }
}
