// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AContractAction$Type } from "./AContractAction";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AContractAction"]: AContractAction$Type;
    ["contracts/actions/AContractAction.sol:AContractAction"]: AContractAction$Type;
  }

  interface ContractTypesMap {
    ["AContractAction"]: GetContractReturnType<AContractAction$Type["abi"]>;
    ["contracts/actions/AContractAction.sol:AContractAction"]: GetContractReturnType<AContractAction$Type["abi"]>;
  }
}
