// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SafeTransferLib$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SafeTransferLib",
  "sourceName": "@solady/utils/SafeTransferLib.sol",
  "abi": [
    {
      "inputs": [],
      "name": "ApproveFailed",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "ETHTransferFailed",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "Permit2AmountOverflow",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "Permit2Failed",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "TransferFailed",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "TransferFromFailed",
      "type": "error"
    }
  ],
  "bytecode": "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212208afe208c4223512aa41f50bac0174df51c66e28b28a8edeabed8663edcbb0dde64736f6c63430008190033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212208afe208c4223512aa41f50bac0174df51c66e28b28a8edeabed8663edcbb0dde64736f6c63430008190033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SafeTransferLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SafeTransferLib$Type["abi"]>>;
  export function deployContract(
    contractName: "@solady/utils/SafeTransferLib.sol:SafeTransferLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SafeTransferLib$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SafeTransferLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SafeTransferLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@solady/utils/SafeTransferLib.sol:SafeTransferLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SafeTransferLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SafeTransferLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SafeTransferLib$Type["abi"]>>;
  export function getContractAt(
    contractName: "@solady/utils/SafeTransferLib.sol:SafeTransferLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SafeTransferLib$Type["abi"]>>;
}
