// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SafeTransferLib$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SafeTransferLib",
  "sourceName": "@solady/utils/SafeTransferLib.sol",
  "abi": [
    {
      "inputs": [],
      "name": "ApproveFailed",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "ETHTransferFailed",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "TransferFailed",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "TransferFromFailed",
      "type": "error"
    }
  ],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220cc6a1ab3474355932b03371977093a2543c974cb6c835de01169979b462dc32664736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220cc6a1ab3474355932b03371977093a2543c974cb6c835de01169979b462dc32664736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SafeTransferLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SafeTransferLib$Type["abi"]>>;
  export function deployContract(
    contractName: "@solady/utils/SafeTransferLib.sol:SafeTransferLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SafeTransferLib$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SafeTransferLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SafeTransferLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@solady/utils/SafeTransferLib.sol:SafeTransferLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SafeTransferLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SafeTransferLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SafeTransferLib$Type["abi"]>>;
  export function getContractAt(
    contractName: "@solady/utils/SafeTransferLib.sol:SafeTransferLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SafeTransferLib$Type["abi"]>>;
}
