// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { AllowList$Type } from "./AllowList";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AllowList"]: AllowList$Type;
    ["contracts/allowlists/AllowList.sol:AllowList"]: AllowList$Type;
  }
}
