// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AllowList$Type } from "./AllowList";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AllowList"]: AllowList$Type;
    ["contracts/allowlists/AllowList.sol:AllowList"]: AllowList$Type;
  }

  interface ContractTypesMap {
    ["AllowList"]: GetContractReturnType<AllowList$Type["abi"]>;
    ["contracts/allowlists/AllowList.sol:AllowList"]: GetContractReturnType<AllowList$Type["abi"]>;
  }
}
