// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IAggregator$Type } from "./IAggregator";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IAggregator"]: IAggregator$Type;
    ["@eth-infinitism/account-abstraction/interfaces/IAggregator.sol:IAggregator"]: IAggregator$Type;
  }
}
