// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { BoostCore$Type } from "./BoostCore";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BoostCore"]: BoostCore$Type;
    ["contracts/BoostCore.sol:BoostCore"]: BoostCore$Type;
  }
}
