// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { TaskManager$Type } from "./TaskManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TaskManager"]: TaskManager$Type;
    ["contracts/avs/TaskManager.sol:TaskManager"]: TaskManager$Type;
  }
}
