// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { SignerValidator$Type } from "./SignerValidator";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SignerValidator"]: SignerValidator$Type;
    ["contracts/validators/SignerValidator.sol:SignerValidator"]: SignerValidator$Type;
  }
}
