// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { BoostError$Type } from "./BoostError";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BoostError"]: BoostError$Type;
    ["contracts/shared/BoostError.sol:BoostError"]: BoostError$Type;
  }
}
