// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ITaskManager$Type } from "./ITaskManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ITaskManager"]: ITaskManager$Type;
    ["contracts/avs/ITaskManager.sol:ITaskManager"]: ITaskManager$Type;
  }
}
