// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface console$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "console",
  "sourceName": "contracts/incentives/ERC1155Incentive.sol",
  "abi": [],
  "bytecode": "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212205afa3efd629e6080c456a64606564d6406c28c1cdfdff02cbaf51989aed1f51164736f6c63430008190033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212205afa3efd629e6080c456a64606564d6406c28c1cdfdff02cbaf51989aed1f51164736f6c63430008190033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "console",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<console$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/incentives/ERC1155Incentive.sol:console",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<console$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "console",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<console$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/incentives/ERC1155Incentive.sol:console",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<console$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "console",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<console$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/incentives/ERC1155Incentive.sol:console",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<console$Type["abi"]>>;
}
