// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Receiver$Type } from "./Receiver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Receiver"]: Receiver$Type;
    ["@solady/accounts/Receiver.sol:Receiver"]: Receiver$Type;
  }
}
