// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Receiver$Type {
  _format: "hh-sol-artifact-1";
  contractName: "Receiver";
  sourceName: "@solady/accounts/Receiver.sol";
  abi: [
    {
      stateMutability: "payable";
      type: "fallback";
    },
    {
      stateMutability: "payable";
      type: "receive";
    },
  ];
  bytecode: "0x";
  deployedBytecode: "0x";
  linkReferences: {};
  deployedLinkReferences: {};
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Receiver",
    constructorArgs?: [],
    config?: DeployContractConfig,
  ): Promise<GetContractReturnType<Receiver$Type["abi"]>>;
  export function deployContract(
    contractName: "@solady/accounts/Receiver.sol:Receiver",
    constructorArgs?: [],
    config?: DeployContractConfig,
  ): Promise<GetContractReturnType<Receiver$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Receiver",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig,
  ): Promise<{
    contract: GetContractReturnType<Receiver$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@solady/accounts/Receiver.sol:Receiver",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig,
  ): Promise<{
    contract: GetContractReturnType<Receiver$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Receiver",
    address: Address,
    config?: GetContractAtConfig,
  ): Promise<GetContractReturnType<Receiver$Type["abi"]>>;
  export function getContractAt(
    contractName: "@solady/accounts/Receiver.sol:Receiver",
    address: Address,
    config?: GetContractAtConfig,
  ): Promise<GetContractReturnType<Receiver$Type["abi"]>>;
}
