// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ECDSA$Type } from "./ECDSA";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ECDSA"]: ECDSA$Type;
    ["@solady/utils/ECDSA.sol:ECDSA"]: ECDSA$Type;
  }
}
