// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { VestingBudget$Type } from "./VestingBudget";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["VestingBudget"]: VestingBudget$Type;
    ["contracts/budgets/VestingBudget.sol:VestingBudget"]: VestingBudget$Type;
  }
}
