// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { VestingBudget$Type } from "./VestingBudget";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["VestingBudget"]: VestingBudget$Type;
    ["contracts/budgets/VestingBudget.sol:VestingBudget"]: VestingBudget$Type;
  }

  interface ContractTypesMap {
    ["VestingBudget"]: GetContractReturnType<VestingBudget$Type["abi"]>;
    ["contracts/budgets/VestingBudget.sol:VestingBudget"]: GetContractReturnType<VestingBudget$Type["abi"]>;
  }
}
