// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ContractAction$Type } from "./ContractAction";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ContractAction"]: ContractAction$Type;
    ["contracts/actions/ContractAction.sol:ContractAction"]: ContractAction$Type;
  }
}
