// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IBoostRegistry$Type } from "./IBoostRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IBoostRegistry"]: IBoostRegistry$Type;
    ["contracts/avs/registry/IBoostRegistry.sol:IBoostRegistry"]: IBoostRegistry$Type;
  }
}
