// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { LibPRNG$Type } from "./LibPRNG";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LibPRNG"]: LibPRNG$Type;
    ["@solady/utils/LibPRNG.sol:LibPRNG"]: LibPRNG$Type;
  }
}
