// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface LibPRNG$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "LibPRNG",
  "sourceName": "@solady/utils/LibPRNG.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122057e75867b9eab68aac6063ad4d21861c0e1edef0e1665a47a2fd7c312907d24464736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122057e75867b9eab68aac6063ad4d21861c0e1edef0e1665a47a2fd7c312907d24464736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "LibPRNG",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LibPRNG$Type["abi"]>>;
  export function deployContract(
    contractName: "@solady/utils/LibPRNG.sol:LibPRNG",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LibPRNG$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "LibPRNG",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LibPRNG$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@solady/utils/LibPRNG.sol:LibPRNG",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LibPRNG$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "LibPRNG",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LibPRNG$Type["abi"]>>;
  export function getContractAt(
    contractName: "@solady/utils/LibPRNG.sol:LibPRNG",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LibPRNG$Type["abi"]>>;
}
