// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface LibPRNG$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "LibPRNG",
  "sourceName": "@solady/utils/LibPRNG.sol",
  "abi": [
    {
      "inputs": [],
      "name": "InvalidInitialLazyShufflerLength",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "InvalidNewLazyShufflerLength",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "LazyShuffleFinished",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "LazyShufflerAlreadyInitialized",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "LazyShufflerGetOutOfBounds",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "LazyShufflerNotInitialized",
      "type": "error"
    }
  ],
  "bytecode": "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212208325be1ac3b1554d0e07ffefdda053beee1894b6e0b770288847cd009b18a93864736f6c634300081a0033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212208325be1ac3b1554d0e07ffefdda053beee1894b6e0b770288847cd009b18a93864736f6c634300081a0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "LibPRNG",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LibPRNG$Type["abi"]>>;
  export function deployContract(
    contractName: "@solady/utils/LibPRNG.sol:LibPRNG",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LibPRNG$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "LibPRNG",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LibPRNG$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@solady/utils/LibPRNG.sol:LibPRNG",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LibPRNG$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "LibPRNG",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LibPRNG$Type["abi"]>>;
  export function getContractAt(
    contractName: "@solady/utils/LibPRNG.sol:LibPRNG",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LibPRNG$Type["abi"]>>;
}
