// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface LibZip$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "LibZip",
  "sourceName": "@solady/utils/LibZip.sol",
  "abi": [],
  "bytecode": "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220dbf980aa76cb02a6abb824b2123f6f09e618957ad76bcd097f5ddd2c2a072a4464736f6c634300081a0033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220dbf980aa76cb02a6abb824b2123f6f09e618957ad76bcd097f5ddd2c2a072a4464736f6c634300081a0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "LibZip",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LibZip$Type["abi"]>>;
  export function deployContract(
    contractName: "@solady/utils/LibZip.sol:LibZip",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LibZip$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "LibZip",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LibZip$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@solady/utils/LibZip.sol:LibZip",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LibZip$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "LibZip",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LibZip$Type["abi"]>>;
  export function getContractAt(
    contractName: "@solady/utils/LibZip.sol:LibZip",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LibZip$Type["abi"]>>;
}
