// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AllowListIncentive$Type } from "./AllowListIncentive";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AllowListIncentive"]: AllowListIncentive$Type;
    ["contracts/incentives/AllowListIncentive.sol:AllowListIncentive"]: AllowListIncentive$Type;
  }

  interface ContractTypesMap {
    ["AllowListIncentive"]: GetContractReturnType<AllowListIncentive$Type["abi"]>;
    ["contracts/incentives/AllowListIncentive.sol:AllowListIncentive"]: GetContractReturnType<AllowListIncentive$Type["abi"]>;
  }
}
