// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IPaymaster$Type } from "./IPaymaster";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IPaymaster"]: IPaymaster$Type;
    ["@eth-infinitism/account-abstraction/interfaces/IPaymaster.sol:IPaymaster"]: IPaymaster$Type;
  }
}
