// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ACGDAIncentive$Type } from "./ACGDAIncentive";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ACGDAIncentive"]: ACGDAIncentive$Type;
    ["contracts/incentives/ACGDAIncentive.sol:ACGDAIncentive"]: ACGDAIncentive$Type;
  }

  interface ContractTypesMap {
    ["ACGDAIncentive"]: GetContractReturnType<ACGDAIncentive$Type["abi"]>;
    ["contracts/incentives/ACGDAIncentive.sol:ACGDAIncentive"]: GetContractReturnType<ACGDAIncentive$Type["abi"]>;
  }
}
