// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Repository$Type } from "./Repository";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Repository"]: Repository$Type;
    ["contracts/Repository.sol:Repository"]: Repository$Type;
  }
}
