// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AAllowListIncentive$Type } from "./AAllowListIncentive";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AAllowListIncentive"]: AAllowListIncentive$Type;
    ["contracts/incentives/AAllowListIncentive.sol:AAllowListIncentive"]: AAllowListIncentive$Type;
  }

  interface ContractTypesMap {
    ["AAllowListIncentive"]: GetContractReturnType<AAllowListIncentive$Type["abi"]>;
    ["contracts/incentives/AAllowListIncentive.sol:AAllowListIncentive"]: GetContractReturnType<AAllowListIncentive$Type["abi"]>;
  }
}
