// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Validator$Type } from "./Validator";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Validator"]: Validator$Type;
    ["contracts/validators/Validator.sol:Validator"]: Validator$Type;
  }

  interface ContractTypesMap {
    ["Validator"]: GetContractReturnType<Validator$Type["abi"]>;
    ["contracts/validators/Validator.sol:Validator"]: GetContractReturnType<Validator$Type["abi"]>;
  }
}
