// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Validator$Type } from "./Validator";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Validator"]: Validator$Type;
    ["contracts/validators/Validator.sol:Validator"]: Validator$Type;
  }
}
