// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Panic$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Panic",
  "sourceName": "@openzeppelin/contracts/utils/Panic.sol",
  "abi": [],
  "bytecode": "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220b543e6ab8c8dfadc2c62e1e4a36294d1c074448169e6207ce1b3c0e7a5f74bfa64736f6c634300081a0033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220b543e6ab8c8dfadc2c62e1e4a36294d1c074448169e6207ce1b3c0e7a5f74bfa64736f6c634300081a0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Panic",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Panic$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Panic.sol:Panic",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Panic$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Panic",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Panic$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Panic.sol:Panic",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Panic$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Panic",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Panic$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Panic.sol:Panic",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Panic$Type["abi"]>>;
}
