// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ServiceManager$Type } from "./ServiceManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ServiceManager"]: ServiceManager$Type;
    ["contracts/avs/ServiceManager.sol:ServiceManager"]: ServiceManager$Type;
  }
}
