// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ServiceManager$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ServiceManager",
  "sourceName": "contracts/avs/ServiceManager.sol",
  "abi": [],
  "bytecode": "0x6080604052348015600e575f80fd5b50603e80601a5f395ff3fe60806040525f80fdfea2646970667358221220fbfb2694ceff7ec7f3347a260182632628b75fd9dbfb7cb5cda9472ec54f452064736f6c63430008190033",
  "deployedBytecode": "0x60806040525f80fdfea2646970667358221220fbfb2694ceff7ec7f3347a260182632628b75fd9dbfb7cb5cda9472ec54f452064736f6c63430008190033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ServiceManager",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ServiceManager$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/avs/ServiceManager.sol:ServiceManager",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ServiceManager$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ServiceManager",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ServiceManager$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/avs/ServiceManager.sol:ServiceManager",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ServiceManager$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ServiceManager",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ServiceManager$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/avs/ServiceManager.sol:ServiceManager",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ServiceManager$Type["abi"]>>;
}
