// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ReentrancyGuard$Type } from "./ReentrancyGuard";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ReentrancyGuard"]: ReentrancyGuard$Type;
    ["@solady/utils/ReentrancyGuard.sol:ReentrancyGuard"]: ReentrancyGuard$Type;
  }

  interface ContractTypesMap {
    ["ReentrancyGuard"]: GetContractReturnType<ReentrancyGuard$Type["abi"]>;
    ["@solady/utils/ReentrancyGuard.sol:ReentrancyGuard"]: GetContractReturnType<ReentrancyGuard$Type["abi"]>;
  }
}
