// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC1271$Type } from "./ERC1271";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC1271"]: ERC1271$Type;
    ["@solady/accounts/ERC1271.sol:ERC1271"]: ERC1271$Type;
  }
}
