// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC721$Type } from "./ERC721";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC721"]: ERC721$Type;
    ["@solady/tokens/ERC721.sol:ERC721"]: ERC721$Type;
  }

  interface ContractTypesMap {
    ["ERC721"]: GetContractReturnType<ERC721$Type["abi"]>;
    ["@solady/tokens/ERC721.sol:ERC721"]: GetContractReturnType<ERC721$Type["abi"]>;
  }
}
