// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC721$Type } from "./ERC721";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC721"]: ERC721$Type;
    ["@solady/tokens/ERC721.sol:ERC721"]: ERC721$Type;
  }
}
