// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { SimpleAllowList$Type } from "./SimpleAllowList";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SimpleAllowList"]: SimpleAllowList$Type;
    ["contracts/allowlists/SimpleAllowList.sol:SimpleAllowList"]: SimpleAllowList$Type;
  }
}
