// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Points$Type } from "./Points";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Points"]: Points$Type;
    ["contracts/tokens/Points.sol:Points"]: Points$Type;
  }
}
