// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Points$Type } from "./Points";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Points"]: Points$Type;
    ["contracts/tokens/Points.sol:Points"]: Points$Type;
  }

  interface ContractTypesMap {
    ["Points"]: GetContractReturnType<Points$Type["abi"]>;
    ["contracts/tokens/Points.sol:Points"]: GetContractReturnType<Points$Type["abi"]>;
  }
}
