// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MockERC1155$Type } from "./MockERC1155";
import { MockERC20$Type } from "./MockERC20";
import { MockERC721$Type } from "./MockERC721";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MockERC1155"]: MockERC1155$Type;
    ["MockERC20"]: MockERC20$Type;
    ["MockERC721"]: MockERC721$Type;
    ["contracts/shared/Mocks.sol:MockERC1155"]: MockERC1155$Type;
    ["contracts/shared/Mocks.sol:MockERC20"]: MockERC20$Type;
    ["contracts/shared/Mocks.sol:MockERC721"]: MockERC721$Type;
  }
}
