// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AERC20Incentive$Type } from "./AERC20Incentive";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AERC20Incentive"]: AERC20Incentive$Type;
    ["contracts/incentives/AERC20Incentive.sol:AERC20Incentive"]: AERC20Incentive$Type;
  }

  interface ContractTypesMap {
    ["AERC20Incentive"]: GetContractReturnType<AERC20Incentive$Type["abi"]>;
    ["contracts/incentives/AERC20Incentive.sol:AERC20Incentive"]: GetContractReturnType<AERC20Incentive$Type["abi"]>;
  }
}
