// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { APointsIncentive$Type } from "./APointsIncentive";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["APointsIncentive"]: APointsIncentive$Type;
    ["contracts/incentives/APointsIncentive.sol:APointsIncentive"]: APointsIncentive$Type;
  }

  interface ContractTypesMap {
    ["APointsIncentive"]: GetContractReturnType<APointsIncentive$Type["abi"]>;
    ["contracts/incentives/APointsIncentive.sol:APointsIncentive"]: GetContractReturnType<APointsIncentive$Type["abi"]>;
  }
}
