// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC1155Utils$Type } from "./ERC1155Utils";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC1155Utils"]: ERC1155Utils$Type;
    ["@openzeppelin/contracts/token/ERC1155/utils/ERC1155Utils.sol:ERC1155Utils"]: ERC1155Utils$Type;
  }
}
