// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IEntryPoint$Type } from "./IEntryPoint";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IEntryPoint"]: IEntryPoint$Type;
    ["@eth-infinitism/account-abstraction/interfaces/IEntryPoint.sol:IEntryPoint"]: IEntryPoint$Type;
  }
}
