// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { LibClone$Type } from "./LibClone";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LibClone"]: LibClone$Type;
    ["@solady/utils/LibClone.sol:LibClone"]: LibClone$Type;
  }
}
