// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface LibClone$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "LibClone",
  "sourceName": "@solady/utils/LibClone.sol",
  "abi": [
    {
      "inputs": [],
      "name": "DeploymentFailed",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "ETHTransferFailed",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "SaltDoesNotStartWith",
      "type": "error"
    }
  ],
  "bytecode": "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122044adfd5ebe74ac2414a655ee1e1f173bb1c472efaeb8fd59b05b8d753e39a6de64736f6c63430008190033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea264697066735822122044adfd5ebe74ac2414a655ee1e1f173bb1c472efaeb8fd59b05b8d753e39a6de64736f6c63430008190033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "LibClone",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LibClone$Type["abi"]>>;
  export function deployContract(
    contractName: "@solady/utils/LibClone.sol:LibClone",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LibClone$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "LibClone",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LibClone$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@solady/utils/LibClone.sol:LibClone",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LibClone$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "LibClone",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LibClone$Type["abi"]>>;
  export function getContractAt(
    contractName: "@solady/utils/LibClone.sol:LibClone",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LibClone$Type["abi"]>>;
}
