// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface LibClone$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "LibClone",
  "sourceName": "@solady/utils/LibClone.sol",
  "abi": [
    {
      "inputs": [],
      "name": "DeploymentFailed",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "ETHTransferFailed",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "SaltDoesNotStartWith",
      "type": "error"
    }
  ],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220e8a9f14335df9a66858e347a936f000212abfad42f23731b143e426923f3884764736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220e8a9f14335df9a66858e347a936f000212abfad42f23731b143e426923f3884764736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "LibClone",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LibClone$Type["abi"]>>;
  export function deployContract(
    contractName: "@solady/utils/LibClone.sol:LibClone",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LibClone$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "LibClone",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LibClone$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@solady/utils/LibClone.sol:LibClone",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LibClone$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "LibClone",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LibClone$Type["abi"]>>;
  export function getContractAt(
    contractName: "@solady/utils/LibClone.sol:LibClone",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LibClone$Type["abi"]>>;
}
