// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { BoostPaymaster$Type } from "./BoostPaymaster";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BoostPaymaster"]: BoostPaymaster$Type;
    ["contracts/accounts/BoostPaymaster.sol:BoostPaymaster"]: BoostPaymaster$Type;
  }
}
