// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Arrays$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Arrays",
  "sourceName": "@openzeppelin/contracts/utils/Arrays.sol",
  "abi": [],
  "bytecode": "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212202f362cca3b8c099b92f3f7bdda6a35b3a437aafeeefc9fd9a059fc689feb097164736f6c63430008190033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212202f362cca3b8c099b92f3f7bdda6a35b3a437aafeeefc9fd9a059fc689feb097164736f6c63430008190033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Arrays",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Arrays$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Arrays.sol:Arrays",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Arrays$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Arrays",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Arrays$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Arrays.sol:Arrays",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Arrays$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Arrays",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Arrays$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Arrays.sol:Arrays",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Arrays$Type["abi"]>>;
}
