// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Arrays$Type } from "./Arrays";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Arrays"]: Arrays$Type;
    ["@openzeppelin/contracts/utils/Arrays.sol:Arrays"]: Arrays$Type;
  }

  interface ContractTypesMap {
    ["Arrays"]: GetContractReturnType<Arrays$Type["abi"]>;
    ["@openzeppelin/contracts/utils/Arrays.sol:Arrays"]: GetContractReturnType<Arrays$Type["abi"]>;
  }
}
