// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ActionSpecLib$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ActionSpecLib",
  "sourceName": "contracts/shared/ActionSpecLib.sol",
  "abi": [],
  "bytecode": "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220dd4b268a3b2a93b1e0260be3ce01933fbab5ee0db0380bdd66c9de007226cbd864736f6c63430008190033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220dd4b268a3b2a93b1e0260be3ce01933fbab5ee0db0380bdd66c9de007226cbd864736f6c63430008190033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ActionSpecLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ActionSpecLib$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/shared/ActionSpecLib.sol:ActionSpecLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ActionSpecLib$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ActionSpecLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ActionSpecLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/shared/ActionSpecLib.sol:ActionSpecLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ActionSpecLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ActionSpecLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ActionSpecLib$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/shared/ActionSpecLib.sol:ActionSpecLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ActionSpecLib$Type["abi"]>>;
}
