// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ActionSpecLib$Type } from "./ActionSpecLib";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ActionSpecLib"]: ActionSpecLib$Type;
    ["contracts/shared/ActionSpecLib.sol:ActionSpecLib"]: ActionSpecLib$Type;
  }
}
