// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ASignerValidator$Type } from "./ASignerValidator";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ASignerValidator"]: ASignerValidator$Type;
    ["contracts/validators/ASignerValidator.sol:ASignerValidator"]: ASignerValidator$Type;
  }

  interface ContractTypesMap {
    ["ASignerValidator"]: GetContractReturnType<ASignerValidator$Type["abi"]>;
    ["contracts/validators/ASignerValidator.sol:ASignerValidator"]: GetContractReturnType<ASignerValidator$Type["abi"]>;
  }
}
