// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { BoostRegistryCoordinator$Type } from "./BoostRegistryCoordinator";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BoostRegistryCoordinator"]: BoostRegistryCoordinator$Type;
    ["contracts/avs/registry/RegistryCoordinator.sol:BoostRegistryCoordinator"]: BoostRegistryCoordinator$Type;
  }
}
