// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface BoostRegistryCoordinator$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "BoostRegistryCoordinator",
  "sourceName": "contracts/avs/registry/RegistryCoordinator.sol",
  "abi": [],
  "bytecode": "0x6080604052348015600e575f80fd5b50603e80601a5f395ff3fe60806040525f80fdfea264697066735822122060fd1c1a007929a33dd186cf6303b2ffd51e54367267d3683b181f865ecb038364736f6c63430008190033",
  "deployedBytecode": "0x60806040525f80fdfea264697066735822122060fd1c1a007929a33dd186cf6303b2ffd51e54367267d3683b181f865ecb038364736f6c63430008190033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "BoostRegistryCoordinator",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<BoostRegistryCoordinator$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/avs/registry/RegistryCoordinator.sol:BoostRegistryCoordinator",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<BoostRegistryCoordinator$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "BoostRegistryCoordinator",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<BoostRegistryCoordinator$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/avs/registry/RegistryCoordinator.sol:BoostRegistryCoordinator",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<BoostRegistryCoordinator$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "BoostRegistryCoordinator",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<BoostRegistryCoordinator$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/avs/registry/RegistryCoordinator.sol:BoostRegistryCoordinator",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<BoostRegistryCoordinator$Type["abi"]>>;
}
