// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BoostRegistry$Type } from "./BoostRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BoostRegistry"]: BoostRegistry$Type;
    ["contracts/BoostRegistry.sol:BoostRegistry"]: BoostRegistry$Type;
  }

  interface ContractTypesMap {
    ["BoostRegistry"]: GetContractReturnType<BoostRegistry$Type["abi"]>;
    ["contracts/BoostRegistry.sol:BoostRegistry"]: GetContractReturnType<BoostRegistry$Type["abi"]>;
  }
}
