// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { BoostRegistry$Type } from "./BoostRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BoostRegistry"]: BoostRegistry$Type;
    ["contracts/BoostRegistry.sol:BoostRegistry"]: BoostRegistry$Type;
  }
}
