// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SimpleDenyList$Type } from "./SimpleDenyList";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SimpleDenyList"]: SimpleDenyList$Type;
    ["contracts/allowlists/SimpleDenyList.sol:SimpleDenyList"]: SimpleDenyList$Type;
  }

  interface ContractTypesMap {
    ["SimpleDenyList"]: GetContractReturnType<SimpleDenyList$Type["abi"]>;
    ["contracts/allowlists/SimpleDenyList.sol:SimpleDenyList"]: GetContractReturnType<SimpleDenyList$Type["abi"]>;
  }
}
