// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { SimpleDenyList$Type } from "./SimpleDenyList";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SimpleDenyList"]: SimpleDenyList$Type;
    ["contracts/allowlists/SimpleDenyList.sol:SimpleDenyList"]: SimpleDenyList$Type;
  }
}
