// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { BoostAccount$Type } from "./BoostAccount";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BoostAccount"]: BoostAccount$Type;
    ["contracts/accounts/BoostAccount.sol:BoostAccount"]: BoostAccount$Type;
  }
}
