// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { LibString$Type } from "./LibString";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LibString"]: LibString$Type;
    ["@solady/utils/LibString.sol:LibString"]: LibString$Type;
  }
}
