// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface LibString$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "LibString",
  "sourceName": "@solady/utils/LibString.sol",
  "abi": [
    {
      "inputs": [],
      "name": "HexLengthInsufficient",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "TooBigForSmallString",
      "type": "error"
    }
  ],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122089050646a651be564616550e570b2e0beff47e78764d1d884bfb83d788d56ee864736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122089050646a651be564616550e570b2e0beff47e78764d1d884bfb83d788d56ee864736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "LibString",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LibString$Type["abi"]>>;
  export function deployContract(
    contractName: "@solady/utils/LibString.sol:LibString",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<LibString$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "LibString",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LibString$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@solady/utils/LibString.sol:LibString",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<LibString$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "LibString",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LibString$Type["abi"]>>;
  export function getContractAt(
    contractName: "@solady/utils/LibString.sol:LibString",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<LibString$Type["abi"]>>;
}
