// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Budget$Type } from "./Budget";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Budget"]: Budget$Type;
    ["contracts/budgets/Budget.sol:Budget"]: Budget$Type;
  }
}
