// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Action$Type } from "./Action";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Action"]: Action$Type;
    ["contracts/actions/Action.sol:Action"]: Action$Type;
  }
}
