// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Action$Type } from "./Action";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Action"]: Action$Type;
    ["contracts/actions/Action.sol:Action"]: Action$Type;
  }

  interface ContractTypesMap {
    ["Action"]: GetContractReturnType<Action$Type["abi"]>;
    ["contracts/actions/Action.sol:Action"]: GetContractReturnType<Action$Type["abi"]>;
  }
}
