// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ASimpleDenyList$Type } from "./ASimpleDenyList";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ASimpleDenyList"]: ASimpleDenyList$Type;
    ["contracts/allowlists/ASimpleDenyList.sol:ASimpleDenyList"]: ASimpleDenyList$Type;
  }

  interface ContractTypesMap {
    ["ASimpleDenyList"]: GetContractReturnType<ASimpleDenyList$Type["abi"]>;
    ["contracts/allowlists/ASimpleDenyList.sol:ASimpleDenyList"]: GetContractReturnType<ASimpleDenyList$Type["abi"]>;
  }
}
