// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Registry$Type } from "./Registry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Registry"]: Registry$Type;
    ["contracts/avs/registry/BoostRegistry.sol:Registry"]: Registry$Type;
  }
}
