// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ShortStrings$Type } from "./ShortStrings";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ShortStrings"]: ShortStrings$Type;
    ["@openzeppelin/contracts/utils/ShortStrings.sol:ShortStrings"]: ShortStrings$Type;
  }
}
