// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { SafeCast$Type } from "./SafeCast";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SafeCast"]: SafeCast$Type;
    ["@openzeppelin/contracts/utils/math/SafeCast.sol:SafeCast"]: SafeCast$Type;
  }

  interface ContractTypesMap {
    ["SafeCast"]: GetContractReturnType<SafeCast$Type["abi"]>;
    ["@openzeppelin/contracts/utils/math/SafeCast.sol:SafeCast"]: GetContractReturnType<SafeCast$Type["abi"]>;
  }
}
