// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IStakeManager$Type } from "./IStakeManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IStakeManager"]: IStakeManager$Type;
    ["@eth-infinitism/account-abstraction/interfaces/IStakeManager.sol:IStakeManager"]: IStakeManager$Type;
  }
}
