// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Initializable$Type } from "./Initializable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Initializable"]: Initializable$Type;
    ["@solady/utils/Initializable.sol:Initializable"]: Initializable$Type;
  }

  interface ContractTypesMap {
    ["Initializable"]: GetContractReturnType<Initializable$Type["abi"]>;
    ["@solady/utils/Initializable.sol:Initializable"]: GetContractReturnType<Initializable$Type["abi"]>;
  }
}
