// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Initializable$Type } from "./Initializable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Initializable"]: Initializable$Type;
    ["@solady/utils/Initializable.sol:Initializable"]: Initializable$Type;
  }
}
