// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Initializable$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Initializable",
  "sourceName": "@solady/utils/Initializable.sol",
  "abi": [
    {
      "inputs": [],
      "name": "InvalidInitialization",
      "type": "error"
    },
    {
      "inputs": [],
      "name": "NotInitializing",
      "type": "error"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "uint64",
          "name": "version",
          "type": "uint64"
        }
      ],
      "name": "Initialized",
      "type": "event"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Initializable",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Initializable$Type["abi"]>>;
  export function deployContract(
    contractName: "@solady/utils/Initializable.sol:Initializable",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Initializable$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Initializable",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Initializable$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@solady/utils/Initializable.sol:Initializable",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Initializable$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Initializable",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Initializable$Type["abi"]>>;
  export function getContractAt(
    contractName: "@solady/utils/Initializable.sol:Initializable",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Initializable$Type["abi"]>>;
}
