// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { UUPSUpgradeable$Type } from "./UUPSUpgradeable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["UUPSUpgradeable"]: UUPSUpgradeable$Type;
    ["@solady/utils/UUPSUpgradeable.sol:UUPSUpgradeable"]: UUPSUpgradeable$Type;
  }
}
