// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { EIP712$Type } from "./EIP712";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EIP712"]: EIP712$Type;
    ["@solady/utils/EIP712.sol:EIP712"]: EIP712$Type;
  }
}
