// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { SignatureCheckerLib$Type } from "./SignatureCheckerLib";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SignatureCheckerLib"]: SignatureCheckerLib$Type;
    ["@solady/utils/SignatureCheckerLib.sol:SignatureCheckerLib"]: SignatureCheckerLib$Type;
  }
}
