// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SignatureCheckerLib$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SignatureCheckerLib",
  "sourceName": "@solady/utils/SignatureCheckerLib.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220b14fd077a0506fbc385b99da46304cbd23d4a0d63c16592f35ce1aed2fb3d1cf64736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220b14fd077a0506fbc385b99da46304cbd23d4a0d63c16592f35ce1aed2fb3d1cf64736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SignatureCheckerLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SignatureCheckerLib$Type["abi"]>>;
  export function deployContract(
    contractName: "@solady/utils/SignatureCheckerLib.sol:SignatureCheckerLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SignatureCheckerLib$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SignatureCheckerLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SignatureCheckerLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@solady/utils/SignatureCheckerLib.sol:SignatureCheckerLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SignatureCheckerLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SignatureCheckerLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SignatureCheckerLib$Type["abi"]>>;
  export function getContractAt(
    contractName: "@solady/utils/SignatureCheckerLib.sol:SignatureCheckerLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SignatureCheckerLib$Type["abi"]>>;
}
