// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SignatureCheckerLib$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SignatureCheckerLib",
  "sourceName": "@solady/utils/SignatureCheckerLib.sol",
  "abi": [],
  "bytecode": "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220569a3bd3b5cb3a54508b7f789993e311b6a9f7f23d0bb4cd321176cdd1df942264736f6c63430008190033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220569a3bd3b5cb3a54508b7f789993e311b6a9f7f23d0bb4cd321176cdd1df942264736f6c63430008190033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SignatureCheckerLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SignatureCheckerLib$Type["abi"]>>;
  export function deployContract(
    contractName: "@solady/utils/SignatureCheckerLib.sol:SignatureCheckerLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SignatureCheckerLib$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SignatureCheckerLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SignatureCheckerLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@solady/utils/SignatureCheckerLib.sol:SignatureCheckerLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SignatureCheckerLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SignatureCheckerLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SignatureCheckerLib$Type["abi"]>>;
  export function getContractAt(
    contractName: "@solady/utils/SignatureCheckerLib.sol:SignatureCheckerLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SignatureCheckerLib$Type["abi"]>>;
}
