// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { UserOperationLib$Type } from "./UserOperationLib";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["UserOperationLib"]: UserOperationLib$Type;
    ["@eth-infinitism/account-abstraction/interfaces/UserOperation.sol:UserOperationLib"]: UserOperationLib$Type;
  }
}
