// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface UserOperationLib$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "UserOperationLib",
  "sourceName": "@eth-infinitism/account-abstraction/interfaces/UserOperation.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122060a8717cebf7a3d30c0309195d1ed5d4f6a055cd786d0381a51de3be8a891d7664736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122060a8717cebf7a3d30c0309195d1ed5d4f6a055cd786d0381a51de3be8a891d7664736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "UserOperationLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<UserOperationLib$Type["abi"]>>;
  export function deployContract(
    contractName: "@eth-infinitism/account-abstraction/interfaces/UserOperation.sol:UserOperationLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<UserOperationLib$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "UserOperationLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<UserOperationLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@eth-infinitism/account-abstraction/interfaces/UserOperation.sol:UserOperationLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<UserOperationLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "UserOperationLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<UserOperationLib$Type["abi"]>>;
  export function getContractAt(
    contractName: "@eth-infinitism/account-abstraction/interfaces/UserOperation.sol:UserOperationLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<UserOperationLib$Type["abi"]>>;
}
