// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC4337$Type } from "./ERC4337";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC4337"]: ERC4337$Type;
    ["@solady/accounts/ERC4337.sol:ERC4337"]: ERC4337$Type;
  }
}
