// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { BoostProxy$Type } from "./BoostProxy";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BoostProxy"]: BoostProxy$Type;
    ["contracts/accounts/BoostProxy.sol:BoostProxy"]: BoostProxy$Type;
  }
}
