// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { OwnableRoles$Type } from "./OwnableRoles";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["OwnableRoles"]: OwnableRoles$Type;
    ["@solady/auth/OwnableRoles.sol:OwnableRoles"]: OwnableRoles$Type;
  }

  interface ContractTypesMap {
    ["OwnableRoles"]: GetContractReturnType<OwnableRoles$Type["abi"]>;
    ["@solady/auth/OwnableRoles.sol:OwnableRoles"]: GetContractReturnType<OwnableRoles$Type["abi"]>;
  }
}
