// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { SimpleBudget$Type } from "./SimpleBudget";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SimpleBudget"]: SimpleBudget$Type;
    ["contracts/budgets/SimpleBudget.sol:SimpleBudget"]: SimpleBudget$Type;
  }
}
