// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Cloneable$Type } from "./Cloneable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Cloneable"]: Cloneable$Type;
    ["contracts/shared/Cloneable.sol:Cloneable"]: Cloneable$Type;
  }
}
