// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Cloneable$Type } from "./Cloneable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Cloneable"]: Cloneable$Type;
    ["contracts/shared/Cloneable.sol:Cloneable"]: Cloneable$Type;
  }

  interface ContractTypesMap {
    ["Cloneable"]: GetContractReturnType<Cloneable$Type["abi"]>;
    ["contracts/shared/Cloneable.sol:Cloneable"]: GetContractReturnType<Cloneable$Type["abi"]>;
  }
}
