name: "🚧 Danger"
on:
  pull_request:
jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOOST_GITHUB_TOKEN }}
      - name: Danger
        uses: danger/danger-js@9.1.8
        env:
          GITHUB_TOKEN: ${{ secrets.BOOST_GITHUB_TOKEN }}
