name: "🚧 Danger"
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize # captures and git pushes with changes
      - edited  # This captures title and description changes
jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOOST_GITHUB_TOKEN }}
      - name: Danger
        uses: danger/danger-js@13.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.BOOST_GITHUB_TOKEN }}
