name: Run Forge Tests
on:
  workflow_call:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2, 3]
        total-shards: [3]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        working-directory: ./packages/evm
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        working-directory: ./packages/evm
        env:
          TEST_SIGNER_PRIVATE_KEY: ${{ secrets.TEST_SIGNER_PRIVATE_KEY }}
        run: |
          forge test -vvv
        id: test
