// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { EnumerableSetLib$Type } from "./EnumerableSetLib";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EnumerableSetLib"]: EnumerableSetLib$Type;
    ["@solady/utils/EnumerableSetLib.sol:EnumerableSetLib"]: EnumerableSetLib$Type;
  }
}
