// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { CGDAIncentive$Type } from "./CGDAIncentive";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CGDAIncentive"]: CGDAIncentive$Type;
    ["contracts/incentives/CGDAIncentive.sol:CGDAIncentive"]: CGDAIncentive$Type;
  }
}
