// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { INonceManager$Type } from "./INonceManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["INonceManager"]: INonceManager$Type;
    ["@eth-infinitism/account-abstraction/interfaces/INonceManager.sol:INonceManager"]: INonceManager$Type;
  }
}
