// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface INonceManager$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "INonceManager",
  "sourceName": "@eth-infinitism/account-abstraction/interfaces/INonceManager.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "sender",
          "type": "address"
        },
        {
          "internalType": "uint192",
          "name": "key",
          "type": "uint192"
        }
      ],
      "name": "getNonce",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "nonce",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint192",
          "name": "key",
          "type": "uint192"
        }
      ],
      "name": "incrementNonce",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "INonceManager",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<INonceManager$Type["abi"]>>;
  export function deployContract(
    contractName: "@eth-infinitism/account-abstraction/interfaces/INonceManager.sol:INonceManager",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<INonceManager$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "INonceManager",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<INonceManager$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@eth-infinitism/account-abstraction/interfaces/INonceManager.sol:INonceManager",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<INonceManager$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "INonceManager",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<INonceManager$Type["abi"]>>;
  export function getContractAt(
    contractName: "@eth-infinitism/account-abstraction/interfaces/INonceManager.sol:INonceManager",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<INonceManager$Type["abi"]>>;
}
